BASE_URL: str
UA: str
NGAPASSPORTUID: str
NGAPASSPORTCID: str
OUTPUT_DIR: str
THREAD_CONFIG_FILE: str

PDF_PAGE_SIZE: str
PDF_PAGE_MARGIN: str
PDF_LONG_IMAGE_MIN_WIDTH: int
PDF_LONG_IMAGE_MIN_RATIO: float
PDF_LONG_IMAGE_SLICE_RATIO: float
PDF_SPEAKER_PORTRAIT_MAX_DIMENSION: int
PDF_SPEAKER_PORTRAIT_MAX_RATIO: float
PDF_SPEAKER_PORTRAIT_SIZE: str

HTML_PRE: str
HTML_POST: str
HTML_STYLE: str
